#!/usr/bin/env bash
# Resolve every third-party image to an immutable digest.
#
# Tech spec §10.5: "Images are pinned by digest, never :latest."
#
# A tag is a mutable pointer. `postgres:16` today and `postgres:16` next month can
# be different bytes, which means a `docker compose pull` can change what is
# running under a gambling ledger without any change in version control. This
# script resolves each tag ONCE and writes the digests to images.env, which IS
# committed. Re-run it deliberately to take an upgrade; never automatically.
#
# Temporal server and admin-tools versions MUST match (§10.5), and the SDK version
# must be compatible with the server — check the compatibility matrix before
# bumping either.
set -euo pipefail

cd "$(dirname "$0")/.."

# ── Versions. Change these deliberately, then re-run. ───────────────────────────
POSTGRES_TAG="postgres:16.10-bookworm"
TEMPORAL_VERSION="1.29.0"
TEMPORAL_SERVER_TAG="temporalio/server:${TEMPORAL_VERSION}"
TEMPORAL_ADMIN_TAG="temporalio/admin-tools:${TEMPORAL_VERSION}-tctl-1.18.4-cli-1.4.2"
TEMPORAL_UI_TAG="temporalio/ui:2.42.1"
CADDY_TAG="caddy:2.10-alpine"
MAILPIT_TAG="axllent/mailpit:v1.28"

resolve() {
  local tag="$1"
  echo "  resolving ${tag}..." >&2
  docker pull --quiet "${tag}" >/dev/null
  docker inspect --format='{{index .RepoDigests 0}}' "${tag}"
}

echo "Resolving image digests (this pulls each image once)..." >&2
POSTGRES_IMAGE="$(resolve "${POSTGRES_TAG}")"
TEMPORAL_SERVER_IMAGE="$(resolve "${TEMPORAL_SERVER_TAG}")"
TEMPORAL_ADMIN_IMAGE="$(resolve "${TEMPORAL_ADMIN_TAG}")"
TEMPORAL_UI_IMAGE="$(resolve "${TEMPORAL_UI_TAG}")"
CADDY_IMAGE="$(resolve "${CADDY_TAG}")"
MAILPIT_IMAGE="$(resolve "${MAILPIT_TAG}")"

cat > compose/images.env <<EOT
# Generated by deploy/bootstrap/pin-digests.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# COMMIT THIS FILE. Re-run the script to take an upgrade; never edit by hand.
#
# Temporal server ${TEMPORAL_VERSION} — admin-tools MUST stay on the same version,
# and the SDK version must be compatible with it (§10.5).
POSTGRES_IMAGE=${POSTGRES_IMAGE}
TEMPORAL_SERVER_IMAGE=${TEMPORAL_SERVER_IMAGE}
TEMPORAL_ADMIN_IMAGE=${TEMPORAL_ADMIN_IMAGE}
TEMPORAL_UI_IMAGE=${TEMPORAL_UI_IMAGE}
CADDY_IMAGE=${CADDY_IMAGE}
MAILPIT_IMAGE=${MAILPIT_IMAGE}
EOT

echo "" >&2
echo "Wrote deploy/compose/images.env:" >&2
sed 's/^/  /' compose/images.env >&2
echo "" >&2
echo "Commit it, then bring the stack up with --env-file compose/images.env." >&2
